---
name: SimpleBannerRUS
version: 0.0.2
main: MaksPV\SimpleBannerRUS\Main
api: 3.0.0

commands:
 banner:
  description: Откройте меню, чтобы создать новый собственный баннер
  permission: simplebannerrus.command.banner
permissions:
 simplebannerrus.command.banner:
  default: op
...
