---
name: SimpleBanner
version: 0.0.2
main: Invy55\SimpleBanner\Main
api: 3.0.0

commands:
 banner:
  description: Откройте меню, чтобы создать новый собственный баннер
  permission: simplebanner.command.banner
permissions:
 simplebanner.command.banner:
  default: op
...
